### ISSUE TITLE
issue with 'NoneType' object, no attribute 'get_newick_repr'

### ISSUE THREAD

**Issue by mlatvis** [FePhyFoFum/phlawd_db_editor#6]
STARTING PYPHLAWD ╰(‘ω’ )╯
LIMITING TO TAXA IN taxalist
MAKING TREE Angiosperms "҉*\( ‘ω’ )/*҉
Traceback (most recent call last):
  File "/gpfs/shared/apps_local/PyPHLAWD/src/get_ncbi_tax_tree_no_species.py", line 98, in <module>
    print(tree.get_newick_repr(False)+";")
AttributeError: 'NoneType' object has no attribute 'get_newick_repr'
Traceback (most recent call last):
  File "/gpfs/shared/apps_local/PyPHLAWD/src/setup_clade.py", line 43, in <module>
    trn = tree_reader.read_tree_file_iter(tname).__next__().label
StopIteration

**Comment by Cactusolo** [comment]
Hi @mlatvis ,

Have you fixed this issue? I saw some discussion in  #2 , but still not helpful --- I got new error with `phlawd_db_editor.py`, when I want to check if the clad exist. 

`python phlawd_db_editor.py -i Pinus -b ../../Projects/PHLAWD_DBS/pln.2023.db
opening logfile phlawd_db_editor.log
connecting to ../../Projects/PHLAWD_DBS/pln.2023.db`

and the log file says:
`Tue, 26 Sep 2023 15:15:13 || creating the phlawd_db_editor_newids table with start value 66600001`
